using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Text.RegularExpressions;
using System.ServiceModel;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using Microsoft.Xrm.Sdk.Metadata;
using Microsoft.Xrm.Sdk.Messages;

namespace DataDictionary
{
    /// <summary>
    /// Plug-in to generate a data dictionary for a specified Dataverse solution.
    /// Retrieves entities, fields, and JavaScript web resources, analyzes script references,
    /// and outputs the result as a JSON file attached to a Note.
    /// </summary>
    public class DataDictionaryPlugin : IPlugin
    {
        /// <summary>
        /// Main entry point for the plug-in.
        /// </summary>
        /// <param name="serviceProvider">Service provider from the Dataverse runtime.</param>
        public void Execute(IServiceProvider serviceProvider)
        {
            ITracingService tracingService = (ITracingService)serviceProvider.GetService(typeof(ITracingService));
            try
            {
                // Obtain the execution context and service
                var context = (IPluginExecutionContext)serviceProvider.GetService(typeof(IPluginExecutionContext));
                var serviceFactory = (IOrganizationServiceFactory)serviceProvider.GetService(typeof(IOrganizationServiceFactory));
                var service = serviceFactory.CreateOrganizationService(context.UserId);

                tracingService.Trace("Starting DataDictionaryPlugin execution.");

                // 1. Get solution unique name from input parameters
                var solutionName = context.InputParameters.Contains("SolutionName") ? context.InputParameters["SolutionName"] as string : null;
                if (string.IsNullOrEmpty(solutionName))
                    throw new InvalidPluginExecutionException("SolutionName parameter is required.");

                tracingService.Trace($"SolutionName: {solutionName}");

                // 2. Retrieve solution and its components (entities, fields, web resources)
                var solutionId = GetSolutionId(service, solutionName, tracingService);
                tracingService.Trace($"SolutionId: {solutionId}");

                var entityMetadatas = GetEntitiesInSolution(service, solutionId, tracingService);
                tracingService.Trace($"Entities found: {entityMetadatas.Count}");

                var fieldMetadatas = GetFieldsInSolution(service, solutionId, entityMetadatas, tracingService);
                tracingService.Trace($"Fields found: {fieldMetadatas.Count}");

                var webResources = GetWebResourcesInSolution(service, solutionId, tracingService);
                tracingService.Trace($"Web resources found: {webResources.Count}");

                // 3. Analyze scripts for field references
                var scriptReferences = AnalyzeScripts(fieldMetadatas, webResources, tracingService);

                // 4. Generate JSON document
                var docBytes = GenerateJsonDocument(fieldMetadatas, scriptReferences);

                // 5. Store document as Note (Annotation) or return as output
                var noteId = StoreDocumentAsNote(service, docBytes, "DataDictionary.json", "Data Dictionary generated by plug-in.", tracingService);

                // Optionally, set output parameter
                context.OutputParameters["NoteId"] = noteId;

                tracingService.Trace("DataDictionaryPlugin execution completed successfully.");
            }
            catch (Exception ex)
            {
                if (serviceProvider != null)
                {
                    tracingService?.Trace($"Exception: {ex}");
                }
                throw new InvalidPluginExecutionException("An error occurred in DataDictionaryPlugin: " + ex.Message, ex);
            }
        }

        /// <summary>
        /// Retrieves the solution ID for a given solution unique name.
        /// </summary>
        /// <param name="service">Organization service.</param>
        /// <param name="solutionName">Unique name of the solution.</param>
        /// <param name="tracingService">Tracing service for logging.</param>
        /// <returns>Solution ID as a Guid.</returns>
        private Guid GetSolutionId(IOrganizationService service, string solutionName, ITracingService tracingService)
        {
            try
            {
                var query = new QueryExpression("solution")
                {
                    ColumnSet = new ColumnSet("solutionid"),
                    Criteria = { Conditions = { new ConditionExpression("uniquename", ConditionOperator.Equal, solutionName) } }
                };
                var result = service.RetrieveMultiple(query).Entities.FirstOrDefault();
                if (result == null)
                    throw new InvalidPluginExecutionException($"Solution '{solutionName}' not found.");
                return result.Id;
            }
            catch (Exception ex)
            {
                tracingService.Trace($"GetSolutionId failed: {ex}");
                throw;
            }
        }

        /// <summary>
        /// Retrieves all entity metadata for entities included in the specified solution.
        /// </summary>
        /// <param name="service">Organization service.</param>
        /// <param name="solutionId">Solution ID.</param>
        /// <param name="tracingService">Tracing service for logging.</param>
        /// <returns>List of EntityMetadata objects.</returns>
        private List<EntityMetadata> GetEntitiesInSolution(IOrganizationService service, Guid solutionId, ITracingService tracingService)
        {
            var entities = new List<EntityMetadata>();
            try
            {
                var query = new QueryExpression("solutioncomponent")
                {
                    ColumnSet = new ColumnSet("objectid"),
                    Criteria =
                    {
                        Conditions =
                        {
                            new ConditionExpression("solutionid", ConditionOperator.Equal, solutionId),
                            new ConditionExpression("componenttype", ConditionOperator.Equal, 1) // 1 = Entity
                        }
                    }
                };
                var entityIds = service.RetrieveMultiple(query).Entities.Select(e => (Guid)e["objectid"]).ToList();

                foreach (var entityId in entityIds)
                {
                    try
                    {
                        var req = new RetrieveEntityRequest
                        {
                            MetadataId = entityId,
                            EntityFilters = EntityFilters.Entity
                        };
                        var resp = (RetrieveEntityResponse)service.Execute(req);
                        if (resp?.EntityMetadata != null)
                            entities.Add(resp.EntityMetadata);
                    }
                    catch (Exception ex)
                    {
                        tracingService.Trace($"Failed to retrieve entity metadata for {entityId}: {ex}");
                    }
                }
            }
            catch (Exception ex)
            {
                tracingService.Trace($"GetEntitiesInSolution failed: {ex}");
                throw;
            }
            return entities;
        }

        /// <summary>
        /// Retrieves all field metadata for fields included in the specified solution and entities.
        /// </summary>
        /// <param name="service">Organization service.</param>
        /// <param name="solutionId">Solution ID.</param>
        /// <param name="entityMetadatas">List of entity metadata.</param>
        /// <param name="tracingService">Tracing service for logging.</param>
        /// <returns>List of FieldMetadata objects.</returns>
        private List<FieldMetadata> GetFieldsInSolution(IOrganizationService service, Guid solutionId, List<EntityMetadata> entityMetadatas, ITracingService tracingService)
        {
            var fields = new List<FieldMetadata>();
            try
            {
                var query = new QueryExpression("solutioncomponent")
                {
                    ColumnSet = new ColumnSet("objectid"),
                    Criteria =
                    {
                        Conditions =
                        {
                            new ConditionExpression("solutionid", ConditionOperator.Equal, solutionId),
                            new ConditionExpression("componenttype", ConditionOperator.Equal, 2) // 2 = Attribute (field)
                        }
                    }
                };
                var attributeIds = service.RetrieveMultiple(query).Entities.Select(e => (Guid)e["objectid"]).ToList();

                foreach (var entity in entityMetadatas)
                {
                    try
                    {
                        var req = new RetrieveEntityRequest
                        {
                            LogicalName = entity.LogicalName,
                            EntityFilters = EntityFilters.Attributes
                        };
                        var resp = (RetrieveEntityResponse)service.Execute(req);
                        if (resp?.EntityMetadata?.Attributes == null)
                            continue;

                        foreach (var attr in resp.EntityMetadata.Attributes)
                        {
                            if (attributeIds.Contains(attr.MetadataId.GetValueOrDefault()) || (attr.IsCustomAttribute ?? false))
                            {
                                fields.Add(new FieldMetadata
                                {
                                    EntityName = entity.LogicalName,
                                    SchemaName = attr.LogicalName,
                                    DisplayName = attr.DisplayName?.UserLocalizedLabel?.Label ?? attr.LogicalName,
                                    Type = attr.AttributeTypeName?.Value ?? attr.AttributeType?.ToString() ?? "",
                                    RequiredLevel = attr.RequiredLevel?.Value.ToString() ?? "",
                                    Description = attr.Description?.UserLocalizedLabel?.Label ?? ""
                                });
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        tracingService.Trace($"Failed to retrieve attributes for entity {entity.LogicalName}: {ex}");
                    }
                }
            }
            catch (Exception ex)
            {
                tracingService.Trace($"GetFieldsInSolution failed: {ex}");
                throw;
            }
            return fields;
        }

        /// <summary>
        /// Retrieves all JavaScript web resources included in the specified solution.
        /// </summary>
        /// <param name="service">Organization service.</param>
        /// <param name="solutionId">Solution ID.</param>
        /// <param name="tracingService">Tracing service for logging.</param>
        /// <returns>List of WebResourceInfo objects.</returns>
        private List<WebResourceInfo> GetWebResourcesInSolution(IOrganizationService service, Guid solutionId, ITracingService tracingService)
        {
            var webResources = new List<WebResourceInfo>();
            try
            {
                var query = new QueryExpression("solutioncomponent")
                {
                    ColumnSet = new ColumnSet("objectid"),
                    Criteria =
                    {
                        Conditions =
                        {
                            new ConditionExpression("solutionid", ConditionOperator.Equal, solutionId),
                            new ConditionExpression("componenttype", ConditionOperator.Equal, 61) // 61 = Web Resource
                        }
                    }
                };
                var webResourceIds = service.RetrieveMultiple(query).Entities.Select(e => (Guid)e["objectid"]).ToList();

                foreach (var id in webResourceIds)
                {
                    try
                    {
                        var wr = service.Retrieve("webresource", id, new ColumnSet("name", "displayname", "description", "content", "webresourcetype"));
                        if (wr.Contains("webresourcetype") && ((OptionSetValue)wr["webresourcetype"]).Value == 3)
                        {
                            var content = wr.Contains("content") ? wr["content"] as string : null;
                            webResources.Add(new WebResourceInfo
                            {
                                Id = id,
                                Name = wr.GetAttributeValue<string>("name"),
                                DisplayName = wr.GetAttributeValue<string>("displayname"),
                                Description = wr.GetAttributeValue<string>("description"),
                                Content = content != null ? Encoding.UTF8.GetString(Convert.FromBase64String(content)) : ""
                            });
                        }
                    }
                    catch (Exception ex)
                    {
                        tracingService.Trace($"Failed to retrieve web resource {id}: {ex}");
                    }
                }
            }
            catch (Exception ex)
            {
                tracingService.Trace($"GetWebResourcesInSolution failed: {ex}");
                throw;
            }
            return webResources;
        }

        /// <summary>
        /// Analyzes JavaScript web resources to find references to fields.
        /// </summary>
        /// <param name="fields">List of field metadata.</param>
        /// <param name="webResources">List of web resources.</param>
        /// <param name="tracingService">Tracing service for logging.</param>
        /// <returns>Dictionary mapping field schema names to lists of web resource names referencing them.</returns>
        private Dictionary<string, List<string>> AnalyzeScripts(List<FieldMetadata> fields, List<WebResourceInfo> webResources, ITracingService tracingService)
        {
            var result = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase);
            try
            {
                foreach (var field in fields)
                {
                    foreach (var wr in webResources)
                    {
                        if (string.IsNullOrEmpty(wr.Content))
                            continue;
                        var pattern = $@"\b{Regex.Escape(field.SchemaName)}\b";
                        if (Regex.IsMatch(wr.Content, pattern, RegexOptions.IgnoreCase))
                        {
                            if (!result.ContainsKey(field.SchemaName))
                                result[field.SchemaName] = new List<string>();
                            result[field.SchemaName].Add(wr.Name);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                tracingService.Trace($"AnalyzeScripts failed: {ex}");
                throw;
            }
            return result;
        }

        /// <summary>
        /// Generates a JSON document containing the data dictionary entries.
        /// </summary>
        /// <param name="fields">List of field metadata.</param>
        /// <param name="scriptReferences">Dictionary of script references per field.</param>
        /// <returns>Byte array of the JSON document.</returns>
        private byte[] GenerateJsonDocument(List<FieldMetadata> fields, Dictionary<string, List<string>> scriptReferences)
        {
            // Compose a serializable structure
            var entries = fields.Select(f => new DataDictionaryEntry
            {
                EntityName = f.EntityName,
                SchemaName = f.SchemaName,
                DisplayName = f.DisplayName,
                Type = f.Type,
                RequiredLevel = f.RequiredLevel,
                Description = f.Description,
                ScriptReferences = scriptReferences.ContainsKey(f.SchemaName) ? scriptReferences[f.SchemaName] : new List<string>()
            }).ToList();

            var serializer = new DataContractJsonSerializer(typeof(List<DataDictionaryEntry>));
            using (var ms = new MemoryStream())
            {
                serializer.WriteObject(ms, entries);
                return ms.ToArray();
            }
        }

        /// <summary>
        /// Stores the generated document as a Note (annotation) in Dataverse.
        /// </summary>
        /// <param name="service">Organization service.</param>
        /// <param name="docBytes">Document content as byte array.</param>
        /// <param name="fileName">File name for the note attachment.</param>
        /// <param name="noteText">Note text/description.</param>
        /// <param name="tracingService">Tracing service for logging.</param>
        /// <returns>GUID of the created annotation record.</returns>
        private Guid StoreDocumentAsNote(IOrganizationService service, byte[] docBytes, string fileName, string noteText, ITracingService tracingService)
        {
            try
            {
                var note = new Entity("annotation");
                note["subject"] = fileName;
                note["notetext"] = noteText;
                note["filename"] = fileName;
                note["mimetype"] = "application/json";
                note["documentbody"] = Convert.ToBase64String(docBytes);
                return service.Create(note);
            }
            catch (Exception ex)
            {
                tracingService.Trace($"StoreDocumentAsNote failed: {ex}");
                throw;
            }
        }

        /// <summary>
        /// Serializable data structure for a data dictionary entry.
        /// </summary>
        [DataContract]
        private class DataDictionaryEntry
        {
            [DataMember] public string EntityName { get; set; }
            [DataMember] public string SchemaName { get; set; }
            [DataMember] public string DisplayName { get; set; }
            [DataMember] public string Type { get; set; }
            [DataMember] public string RequiredLevel { get; set; }
            [DataMember] public string Description { get; set; }
            [DataMember] public List<string> ScriptReferences { get; set; }
        }

        /// <summary>
        /// Helper class for field metadata.
        /// </summary>
        private class FieldMetadata
        {
            public string EntityName { get; set; }
            public string SchemaName { get; set; }
            public string DisplayName { get; set; }
            public string Type { get; set; }
            public string RequiredLevel { get; set; }
            public string Description { get; set; }
        }

        /// <summary>
        /// Helper class for web resource information.
        /// </summary>
        private class WebResourceInfo
        {
            public Guid Id { get; set; }
            public string Name { get; set; }
            public string DisplayName { get; set; }
            public string Description { get; set; }
            public string Content { get; set; }
        }
    }
}